### ISSUE TITLE
Bug: translate (and maybe other methods) do not work with a matrix keyframe

### ISSUE THREAD

**Issue by matsko** [web-animations/web-animations-js#144] opened 2017-06-13 22:38 UTC
I have an example here of an animation using `transform: translate3d(...)` and `transform:matrix(...)` as keyframes and this fails with the polyfill while working perfectly with the native web animations code in Chrome/FF.

https://plnkr.co/edit/sMtptHhdBHQFFiWzCwqb?p=preview

Please let us know if this can be fixed with the polyfill. This is something we need urgently fixed with Angular.

**Comment by macjohnny** [comment] 2017-06-15 05:52
a fix for this bug would also resolve https://github.com/angular/material2/issues/4562#issuecomment-301504744

**Comment by matsko** [comment] 2017-06-15 23:58
@alancutter this hasn't been picked up yet and it's causing an issue with Angular. Could you please have a look?

**Comment by ewilligers** [comment] 2017-06-23 08:22
Matrix interpolation contributes about 12kb of optional size to the polyfill. 

49673 web-animations-next-lite.min.js
61835 web-animations-next.min.js

**Comment by fxck** [comment] 2017-10-24 11:27
@alancutter could this get some attention, please. It would be a huge help, it's making safari animations unsable.

**Comment by stvn100** [comment] 2017-11-04 03:48
Same issue here. Moreover, changing background-color with rgba syntax does not work in Safari even without using keyframes.

**Comment by ewilligers** [comment] 2017-11-04 04:39
We had intentionally removed matrix interpolation from the polyfill to reduce download size.

> changing background-color with rgba syntax does not work in Safari even without using keyframes.

Please raise a separate issue, and include an example.

**Comment by fxck** [comment] 2017-11-06 08:54
Not sure I follow @ewilligers, does this mean that the problem @matsko described is caused by using a version of web-animation-js that doesn't include matrix interpolation?

**Comment by ewilligers** [comment] 2017-11-07 17:34
https://github.com/web-animations/web-animations-js/tree/master
has both
- web-animations-next-lite.min.js
- web-animations-next.min.js (supports matrix interpolation)

**Closed by ewilligers** 2017-11-07 17:34 UTC

**Comment by fxck** [comment] 2017-11-13 13:26
@ewilligers https://stackblitz.com/edit/burger-menu?file=polyfills.ts same problem when using `-next`, are you sure the bug @matsko is describing is related? This makes half fo angular animations unusable on safari. It would be really nice if it could get a fix.

**Comment by oliverjanik** [comment] 2018-05-21 01:34
When will this be released?
