### ISSUE TITLE
TypeError: Cannot assign to read only property 'target' of object '#<AnimationPlaybackEvent>'

### ISSUE THREAD

**Issue by web-padawan** [web-animations/web-animations-js#123] opened 2017-04-13 07:11 UTC
This error appears with latest `2.2.3` release.

```
TypeError: Cannot assign to read only property 'target' of object '#<AnimationPlaybackEvent>'
```

Not yet managed to create a small repro, will investigate.

**Comment by frenchynz** [comment] 2017-04-13 08:18
+1

Had to downgrade our version to 2.2.0 to get things working (2.2.2 may work). Had the boss yelling down my ear at this one! (CI live site deploy for-the-fail 😭 )

**Comment by LarsDenBakker** [comment] 2017-04-13 10:20
We have this error as well.

**Comment by gmcinalli** [comment] 2017-04-13 10:31
Me too, I had to downgrade to 2.2.2.

**Comment by misterzorgy** [comment] 2017-04-13 11:06
Yeah..downgraded to 2.2.2

**Comment by astateful** [comment] 2017-04-13 11:52
Just curious, what behavior is affected by this error? Currently I only see this error when clicking on paper-icon-buttons, and at least the functionality appears to be intact.

**Comment by web-padawan** [comment] 2017-04-13 12:12
Some elements using animations like `paper-menu-button`, `paper-dropdown-menu`, `paper-dialog` etc are broken and might not open at all.

**Comment by abdonrd** [comment] 2017-04-13 12:18
I have the same problem!

**Comment by ronnyroeller** [comment] 2017-04-13 13:42
Same issue here

**Comment by PascalLaier** [comment] 2017-04-13 15:29
Up! 2.2.3 Breaks almost every Polymer app.

**Comment by samuelli** [comment] 2017-04-14 00:05
This has been fixed in #124. Please update to 2.2.4!

**Comment by emilio-martinez** [comment] 2017-04-14 19:23
@samuelli FYI, I'm not seeing 2.2.4 deployed in npm

**Comment by samuelli** [comment] 2017-04-14 20:32
cc @alancutter: looks like NPM publishing didn't work. Can you re-publish to NPM? Thanks.

**Comment by alancutter** [comment] 2017-04-15 22:35
Apologies. The npm release should be at 2.2.4 now.

**Comment by emilio-martinez** [comment] 2017-04-18 12:04
@alancutter thank you!

**Comment by lousley** [comment] 2017-04-18 16:22
this problem isn't fix with 2.2.4 --> tested with paper-dialog and i have the same error message!

**Comment by samuelli** [comment] 2017-04-18 16:59
@lousley: can you provide reproduction steps?

Can you run `cat bower_components/web-animations-js/History.md | head -1` to confirm the version of web-animations that you have? I tried paper-dialog and don't see any errors.

**Comment by lousley** [comment] 2017-04-19 10:44
I found the problem in the library web-animations-next-lite.min.js.gz! Is it possible that you have forgot update the .gz file?

**Comment by alancutter** [comment] 2017-04-20 02:59
Uhoh, the .gz file isn't even supposed to be there. The [release instructions](https://github.com/web-animations/web-animations-js/blob/dev/CONTRIBUTING.md#publishing-a-release) should probably be updated to use `*.min.js{,.map}` instead of `*.min.js*` to avoid picking up more files than intended.

**Comment by lousley** [comment] 2017-04-20 06:20
ah ok :) do you make a new version?

**Comment by alancutter** [comment] 2017-04-20 08:07
Thanks for reporting the mishap, removed the erroneous *.gz files in https://github.com/web-animations/web-animations-js/releases/tag/2.2.5.

**Closed by alancutter** 2017-04-20 08:07 UTC

**Comment by lousley** [comment] 2017-04-20 08:39
@alancutter thank you!

**Comment by BorntraegerMarc** [comment] 2017-06-01 08:35
I am experiencing this issue again when I updated all my dependencies to Polymer 2.0. Has anybody also experienced this issue again in Polymer 2.0?

**Comment by BorntraegerMarc** [comment] 2017-06-01 08:37
BTW: The warning in the console disappears when I add the import `<link rel="import" href="assets/bower_components/neon-animation/web-animations.html">` manually but the scroll issue persists. So it breaks my app at the moment...

**Comment by samuelli** [comment] 2017-06-01 16:46
@BorntraegerMarc: can you remove your `bower_components` and run `bower install` again?

If it's still broken can you dump your `bower.json` and the contents of `bower list`?

**Comment by BorntraegerMarc** [comment] 2017-06-01 16:52
@samuelli Thanks for the fast feedback. I did as you asked but the error still persists. Here is the dump of my dependencies:
```
"dependencies": {
    "app-layout": "PolymerElements/app-layout#2.0.0",
    "iron-flex-layout": "PolymerElements/iron-flex-layout#2.0.0",
    "paper-checkbox": "PolymerElements/paper-checkbox#2.0.0",
    "paper-styles": "PolymerElements/paper-styles#2.0.0",
    "paper-icon-button": "PolymerElements/paper-icon-button#2.0.0",
    "polymer": "Polymer/polymer#2.0.0",
    "iron-icons": "PolymerElements/iron-icons#2.0.0",
    "paper-button": "PolymerElements/paper-button#2.0.0",
    "paper-dialog": "PolymerElements/paper-dialog#2.0.0",
    "paper-input": "PolymerElements/paper-input#2.0.0",
    "paper-card": "PolymerElements/paper-card#2.0.0",
    "paper-toast": "PolymerElements/paper-toast#2.0.0",
    "paper-item": "PolymerElements/paper-item#2.0.0",
    "paper-ripple": "PolymerElements/paper-ripple#2.0.0",
    "paper-menu-button": "PolymerElements/paper-menu-button#2.0.0",
    "paper-dialog-scrollable": "PolymerElements/paper-dialog-scrollable#2.0.0",
    "vaadin-upload": "v2.0.0-alpha3",
    "iron-collapse": "PolymerElements/iron-collapse#2.0.0",
    "font-roboto": "PolymerElements/font-roboto-local#1.0.1",
    "iron-dropdown": "PolymerElements/iron-dropdown#2.0.0",
    "paper-spinner": "PolymerElements/paper-spinner#2.0.0",
    "paper-search": "Collaborne/paper-search#1.4.0",
    "paper-listbox": "PolymerElements/paper-listbox#2.0.0",
    "web-animations-js": "web-animations/web-animations-js#2.2.5",
    "paper-avatar": "Abe90/paper-avatar#1.0.3"
  }
```

I already had the issue with version 2.2.3 and Polymer 1. But then with the next released the issue got fixed and now after the upgrade I experience the error again.

**Comment by BorntraegerMarc** [comment] 2017-06-01 16:53
I think this element https://github.com/PolymerElements/iron-dropdown/issues/132 uses web-animations-js and caused it to fail, maybe?

**Comment by Serginho** [comment] 2020-01-20 15:02
Same problem using `angular@8.2.14` with `"web-animations-js": "^2.3.2"` when I use in the tsconfig.json `"target": "es2015"`

```
Uncaught TypeError: Cannot assign to read only property 'target' of object '[object AnimationPlaybackEvent]'
    at push../node_modules/web-animations-js/web-animations-next.min.js.b.Animation.<anonymous> (web-animations-next.min.js:15)
    at ZoneDelegate.invokeTask (zone-evergreen.js:391)
    at Object.onInvokeTask (core.js:39680)
    at ZoneDelegate.invokeTask (zone-evergreen.js:390)
    at Zone.runTask (zone-evergreen.js:168)
    at ZoneTask.invokeTask [as invoke] (zone-evergreen.js:465)
    at invokeTask (zone-evergreen.js:1603)
    at Animation.globalZoneAwareCallback (zone-evergreen.js:1629)
```

Any fix?
